--- #YAML:1.0
name:               Symbol-Glob
version:            0.03
abstract:           remove items from the symbol table, painlessly
author:
    - Joe McMahon <mcmahon@yahoo-inc.com >
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Exception:  0
    Test::More:       0
    version:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
